# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUezoXCv26ydTC3MHpcXD__CYIvofxm6
"""

class mahasiswa:

   def __init__(self,nama,angkatan,nim):

        self.nama = nama
        self.nim = nim
        self.angkatan = angkatan

   def biodata_mahasiswa(self):
       print("\nnama kamu adalah : ",self.nama)
       print("nim kamu adalah : ",self.nim)
       print("angkatan kamu adalah : ",self.angkatan)

nama = str(input("masukan nama mu : "))
nim = str(input("masukan nim kamu : "))
angkatan = str(input("masukan angkatan kamu: "))

biodata = mahasiswa(nama,angkatan,nim)
biodata.biodata_mahasiswa()

class mahasiswa:

    def __init__(self,nilai,nama):

        self.nilai = nilai
        self.nama = nama


    def ubah(self):

        print("Nama Kamu Adalah : " + self.nama)
        print("nilai kamu adalah : " + str(self.nilai))



perulangan = 0

while perulangan == 0 :

    print("\n==== Program OOP ==== ")
    print("1.Mendeklarasikan Objek")
    print("2.Menampilkan Objek")
    print("3.Mengganti Objek")
    print("4.Menghapus Objek")
    print("5.Menutup Program")

    pilihan = int(input("Masukan Pilihan kamu (1/2/3/4/5) :  "))

    if pilihan == 1 :

        nama = str(input("Masukan Nama Kamu : "))
        nilai = str(input("Masukan Nilai Kamu : "))
        biodata = mahasiswa(nilai,nama)
        print("Data Berhasil Ditambahkan")

    elif pilihan == 2 :

        biodata = mahasiswa(nilai,nama)
        biodata.ubah()

    elif pilihan == 3 :

        a = "nama"
        b = "nilai"


        print("A : Nama")
        print("B : Nilai")
        perubahan = input("masukan pilihan : ")

        if perubahan == "a":

            nama = (input("masukan Nama yang ingin dirubah : "))

            print("Nama Berhasil Dirubah")

        elif perubahan == "b":

            nilai = (input("masukan nilai yang ingin dirubah : "))

            print("Nilai Berhasil Dirubah")

        else:
            print("Masukan Pilihan Yang Terdaftar Diatas")

    elif pilihan == 4 :

        nama = "none"
        nilai = "none"
        print("data berhasil di hapus")

    elif pilihan == 5:
        print("terima kasih telah menggunakan program")
        break